{{$image := DefaultParam .CL2_BENCHMARK_IMAGE "gcr.io/k8s-testimages/perf-tests-util/request-benchmark:latest"}}
{{$cpu := DefaultParam .cpu "400m"}}
{{$memory := DefaultParam .memory "800Mi"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: benchmark
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        name: {{.Name}}
        group: benchmark
    spec:
      containers:
      - name: {{.Name}}
        image: {{$image}}
        imagePullPolicy: Always
        args:
        - --inflight={{.Inflight}}
        - --namespace={{.Namespace}}
        - --uri={{.Uri}}
        - --qps={{.QPS}}
        resources:
          requests:
            cpu: {{$cpu}}
            memory: {{$memory}}
          limits:
            cpu: {{$cpu}}
            memory: {{$memory}}
