{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}

# Endpoints object for the kubemark/kube-apiserver service. For details, see the service object yaml
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kubemark
  name: kubemark-master
  labels:
    instance: kubemark-master
subsets:
  - addresses:
    {{range .MasterIps}}
      - ip: {{.}}
    {{end}}
    ports:
      - name: apiserver
        port: 443
      - name: etcd
        port: 2379
      - name: kubelet
        port: 10250
      - name: kube-scheduler
        port: 10251
      - name: kube-controller-manager
        port: 10252
      {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
      - name: node-exporter
        port: 9100
      {{end}}
