{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: kubemark-master
  name: kubemark-master
  namespace: monitoring
spec:
  jobLabel: instance
  namespaceSelector:
    matchNames:
      - kubemark
  selector:
    matchLabels:
      instance: kubemark-master
  endpoints:
  - interval: 5s
    port: apiserver
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: etcd
  - interval: 5s
    port: kubelet
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kubelet
    path: metrics/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kube-scheduler
  - interval: 5s
    port: kube-controller-manager
  {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
  # TODO(mborsz): Debug why node-exporter is that slow and change interval back to 5s.
  - interval: 30s
    port: node-exporter
    scrapeTimeout: 20s
  {{end}}
