branches:
  only:
    - master

services:
    - docker

language: go

matrix:
    include:
        - go: 1.11

before_install:
    - sudo apt-get install jq

install:
# Create and move build under the go path
    - mkdir -p $HOME/gopath/src/k8s.io
    - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/perf-tests
    - verify/install-verify-tools.sh
    - export PATH=$GOPATH/bin:$PATH

script:
    - ./verify/verify-boilerplate.sh
    - ./verify/verify-gofmt.sh
    - ./verify/verify-golint.sh
    - ./verify/verify-flags-underscore.py
    - ./verify/verify-dashboard-format.sh
    - travis_wait ./verify/go-build.sh
    - ./verify/test.sh
