{{$PROMETHEUS_SCRAPE_KUBE_PROXY := DefaultParam .PROMETHEUS_SCRAPE_KUBE_PROXY true}}

{{if $PROMETHEUS_SCRAPE_KUBE_PROXY}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: monitoring
spec:
  endpoints:
    # We modify interval depending on the cluster size to avoid collecting too many samples for
    # large clusters. Also because the tests run longer in bigger clusters we don't need to
    # collect them as often as in smaller clusters. We use 30s interval for small clusters
    # (# nodes <= 1000) and 1min interval in big clusters (# nodes > 1000)
    # TODO(mm4tt): Once we prove the interval works in big clusters, simplify the expression.
    - interval: {{MinInt 60 (MultiplyInt 30 (AddInt 1 (DivideInt .Nodes 1001)))}}s
      port: http-metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-proxy
{{end}}
