apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probes
  name: dns
  labels:
    probe: dns
spec:
  selector:
    matchLabels:
      probe: dns
  replicas: {{.Replicas}}
  template:
    metadata:
      labels:
        probe: dns
    spec:
      containers:
        - name: dns
          image: gcr.io/k8s-testimages/probes:v0.0.4
          args:
            - --metric-bind-address=0.0.0.0:8080
            - --mode=dns
            # Instead of creating dedicated "null-service" use one that's already exists
            # TODO(oxddr): according to @wojtek-t there are differences between fully and not fully qualified domain names
            # Investigate it and potentially measure latency for both
            - --dns-probe-url=ping-server.probes
            - --logtostderr=false
            - --log_file=/var/log/cl2-dns-lookup.log
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: metrics
          volumeMounts:
            - name: logs-volume
              mountPath: /var/log
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log
