apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    group: load
spec:
  podSelector:
    matchLabels:
      name: {{.PodSelectorLabelValue}}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{.CIDR}}
    ports:
    # Use two ports to double the number of load network policy rules.
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 6355
