# To mitigate https://github.com/kubernetes/kubernetes/issues/96635 we have to delete
# configmaps and secrets only AFTER the pods using that configmap/secret are deleted.
# TODO(mborsz): Merge this back to reconcile-objects/config.yaml once the issue above is fixed.

{{$actionName := printf "%s objects" .actionName}}
{{$namespaces := .namespaces}}
{{$tuningSet := .tuningSet}}

{{$bigDeploymentsPerNamespace := .bigDeploymentsPerNamespace}}
{{$mediumDeploymentsPerNamespace := .mediumDeploymentsPerNamespace}}
{{$smallDeploymentsPerNamespace := .smallDeploymentsPerNamespace}}

steps:
- name: {{$actionName}} configmaps and secrets
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$bigDeploymentsPerNamespace}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: big-deployment
      objectTemplatePath: /modules/configmaps-secrets/configmap.yaml
    - basename: big-deployment
      objectTemplatePath: /modules/configmaps-secrets/secret.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$mediumDeploymentsPerNamespace}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: medium-deployment
      objectTemplatePath: /modules/configmaps-secrets/configmap.yaml
    - basename: medium-deployment
      objectTemplatePath: /modules/configmaps-secrets/secret.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$smallDeploymentsPerNamespace}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: small-deployment
      objectTemplatePath: /modules/configmaps-secrets/configmap.yaml
    - basename: small-deployment
      objectTemplatePath: /modules/configmaps-secrets/secret.yaml
