{{$PROMETHEUS_SCRAPE_ETCD := DefaultParam .PROMETHEUS_SCRAPE_ETCD false}}
{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: master
  name: master
  namespace: monitoring
spec:
  endpoints:
  {{if $PROMETHEUS_SCRAPE_ETCD}}
  - interval: 5s
    port: etcd
  {{end}}
  {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
  - interval: 5s
    port: node-exporter
  {{end}}
  - interval: 5s
    port: kubelet
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kubelet
    path: metrics/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: master
