## Services module provides a module for creating / deleting services.

## Input params
{{$actionName := .actionName}}
{{$namespaces := .namespaces}}
{{$smallServicesPerNamespace := .smallServicesPerNamespace}}
{{$mediumServicesPerNamespace := .mediumServicesPerNamespace}}
{{$bigServicesPerNamespace := .bigServicesPerNamespace}}

steps:
- name: "{{$actionName}} k8s services"
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$bigServicesPerNamespace}}
    tuningSet: Sequence
    objectBundle:
    - basename: big-service
      objectTemplatePath: service.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$mediumServicesPerNamespace}}
    tuningSet: Sequence
    objectBundle:
    - basename: medium-service
      objectTemplatePath: service.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$smallServicesPerNamespace}}
    tuningSet: Sequence
    objectBundle:
    - basename: small-service
      objectTemplatePath: service.yaml
