apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probes
  name: ping-server
  labels:
    probe: ping-server
spec:
  selector:
    matchLabels:
      probe: ping-server
  replicas: {{.Replicas}}
  template:
    metadata:
      labels:
        probe: ping-server
    spec:
      containers:
        - name: ping-server
          image: gcr.io/k8s-testimages/probes:v0.0.4
          args:
            - --metric-bind-address=0.0.0.0:8080
            - --mode=ping-server
            - --ping-server-bind-address=0.0.0.0:8081
            - --logtostderr=false
            - --log_file=/var/log/cl2-ping-server.log
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: http
          volumeMounts:
            - name: logs-volume
              mountPath: /var/log
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log
