{{$PROMETHEUS_SCRAPE_ETCD := DefaultParam .PROMETHEUS_SCRAPE_ETCD false}}
{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: master
  name: master
  namespace: monitoring
spec:
  endpoints:
  {{if $PROMETHEUS_SCRAPE_ETCD}}
  - interval: 5s
    port: etcd-2379
  - interval: 5s
    port: etcd-2382
  {{end}}
  {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
  # TODO(mborsz): Debug why node-exporter is that slow and change interval back to 5s.
  - interval: 30s
    port: node-exporter
    scrapeTimeout: 20s
  {{end}}
  - interval: 5s
    port: apiserver
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kubelet
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kubelet
    path: /metrics/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - interval: 5s
    port: kube-scheduler
  - interval: 5s
    port: kube-controller-manager
  selector:
    k8s-app: master
